MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test", )
SOLVER:
  LR_EPOCHS: [154, 193]
  BATCH_SIZE: 32
  LR: 1e-3 
  
GPU: '0'
CKPT: null
DATA_DIR: './data/pascal_voc/VOCdevkit'
OUTPUT_DIR: 'LOGS'
